apiVersion: v1
kind: Service
metadata:
  name: {{ include "rdf4j.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "rdf4j.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rdf4j.service.type }}
  ports:
    - port: {{ .Values.rdf4j.service.port }}
      targetPort: {{ .Values.rdf4j.service.targetPort }}
      protocol: {{ .Values.rdf4j.service.protocol }}
      {{- if and (or (eq .Values.rdf4j.service.type "NodePort") (eq .Values.rdf4j.service.type "Loardf4jalancer")) (not (empty .Values.rdf4j.service.nodePort)) }}
      nodePort: {{ .Values.rdf4j.service.nodePort }}
      {{ end }}
  selector:
    {{- include "rdf4j.selectorLabels" . | nindent 4 }}