apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rdf4j.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "rdf4j.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "rdf4j.fullname" . }}-headless
  {{- if not .Values.rdf4j.autoscaling.enabled }}
  replicas: {{ .Values.rdf4j.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rdf4j.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rdf4j.labels" . | nindent 8 }}
    spec:
      {{- with .Values.rdf4j.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.global.nodeSelectorLabel }}
      nodeSelector:
          nodeSelectorLabel: {{ .Values.global.nodeSelectorLabel | quote }}
      {{- end }}
      {{- with .Values.rdf4j.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rdf4j.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.rdf4j.podSecurityContext | nindent 8 }}
      containers:
        - name: rdf4j
          securityContext:
            {{- toYaml .Values.rdf4j.securityContext | nindent 12 }}
          image: "{{ .Values.rdf4j.image.repository }}:{{ .Values.rdf4j.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.rdf4j.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.rdf4j.service.containerPort }}
              protocol: {{ .Values.rdf4j.service.protocol }}
          resources:
            {{- toYaml .Values.rdf4j.resources | nindent 12 }}
          volumeMounts:
            - name: "info-{{include "rdf4j.fullname" .}}"
              mountPath: {{ .Values.rdf4j.persistenceInfo.mountPath | quote }}
            - name: "rdf4j-data-{{include "rdf4j.fullname" .}}"
              mountPath: {{ .Values.rdf4j.persistence.mountPath | quote }}
            - name: "logs-{{include "rdf4j.fullname" .}}"
              mountPath: {{ .Values.rdf4j.persistenceLogs.mountPath | quote }}
          {{- with .Values.rdf4j.envVars }}
          env:
            - name: JAVA_OPTS
              value: "-Dorg.eclipse.rdf4j.client.http.connectionTimeout=10000 -Dorg.eclipse.rdf4j.client.http.connectionRequestTimeout=10000 -Dorg.eclipse.rdf4j.client.http.socketTimeout=10000"
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: "rdf4j-data-{{include "rdf4j.fullname" .}}"
      spec:
        accessModes:
        {{- range .Values.rdf4j.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.rdf4j.persistence.size | quote }}
    - metadata:
        name: "logs-{{include "rdf4j.fullname" .}}"
      spec:
        accessModes:
        {{- range .Values.rdf4j.persistenceLogs.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.rdf4j.persistenceLogs.size | quote }}
    - metadata:
        name: "info-{{include "rdf4j.fullname" .}}"
      spec:
        accessModes:
        {{- range .Values.rdf4j.persistenceInfo.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.rdf4j.persistenceInfo.size | quote }}