
server:
  global:
    scrape_interval: 1s
    scrape_timeout: 1s
  service:
    type: NodePort
    nodePort: "31165"

      
  remoteWrite:
    - url: http://vms-victoria-metrics-single-server:8428/api/v1/write

extraScrapeConfigs: |
  - job_name: 'registry-pods'
    scrape_interval: 1s
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - default
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
        action: keep
        regex: application
        target_label: component
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        action: keep
        regex: registry
        target_label: name
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
        target_label: component
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        target_label: name
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
        target_label: instance
      - source_labels: [__address__]
        regex: (.+):\d+
        target_label: __address__
        replacement: $1:9293

  - job_name: 'query-pods'
    scrape_interval: 1s
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - default
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
        action: keep
        regex: application
        target_label: component
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        action: keep
        regex: query
        target_label: name
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
        target_label: component
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        target_label: name
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
        target_label: instance
      - source_labels: [__address__]
        regex: (.+):\d+
        target_label: __address__
        replacement: $1:9394

  - job_name: 'kubelet-resource'
    scheme: https
    kubernetes_sd_configs:
      - role: node
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    relabel_configs:
      # Point at the apiserver and set per-node metrics path
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/resource
