apiVersion: v1
kind: ConfigMap
metadata:
  name: "setting-{{ include "application.fullname" . }}"
data:
  setting.trig: |
    @prefix this: <https://w3id.org/np/RA8DQemv3WwH2K_YON_fnyyVvWVnxaTFFU4YAFW6gFyc4> .
    @prefix sub: <https://w3id.org/np/RA8DQemv3WwH2K_YON_fnyyVvWVnxaTFFU4YAFW6gFyc4#> .
    @prefix np: <http://www.nanopub.org/nschema#> .
    @prefix dct: <http://purl.org/dc/terms/> .
    @prefix nt: <https://w3id.org/np/o/ntemplate/> .
    @prefix npx: <http://purl.org/nanopub/x/> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    @prefix orcid: <https://orcid.org/> .
    @prefix prov: <http://www.w3.org/ns/prov#> .
    @prefix foaf: <http://xmlns.com/foaf/0.1/> .

    sub:Head {
    this: np:hasAssertion sub:assertion;
        np:hasProvenance sub:provenance;
        np:hasPublicationInfo sub:pubinfo;
        a np:Nanopublication .
    }

    sub:assertion {
    sub:setting npx:hasAgents <https://w3id.org/np/RA87n-fHjNmYTYRYBE7xER4HzsA_S7nf2qnQC4irqxxhY>;
        npx:hasBootstrapService <http://130.60.24.146:7880/>, <http://server.np.dumontierlab.com/>,
        <https://np.knowledgepixels.com/>, <https://server.np.trustyuri.net/>;
        npx:hasServices <http://purl.org/np/RA6H6eWp93TQHxpPEiSO2WsVBJCXTQSyjaD68JMz5OVtY>;
        npx:hasTrustRangeAlgorithm npx:TransitiveTrust;
        npx:hasUpdateStrategy npx:UpdatesByCreator;
        a npx:NanopubSetting;
        rdfs:label "first nanopublication setting" .
    }

    sub:provenance {
    sub:assertion prov:wasAttributedTo orcid:0000-0002-1267-0234 .
    }

    sub:pubinfo {
    orcid:0000-0002-1267-0234 foaf:name "Tobias Kuhn" .
    
    sub:sig npx:hasAlgorithm "RSA";
        npx:hasPublicKey "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQD4Wj537OijfOWVtsHMznuXKISqBhtGDQZfdO6pbb4hg9EHMcUFGTLbWaPrP783PHv8HMAAPjvEkHLaOHMIknqhaIa5236lfBO3r+ljVdYBElBcLvROmwG+ZGtmPNZf7lMhI15xf5TfoaSa84AFRd5J2EXekK6PhaFQhRm1IpSYtwIDAQAB";
        npx:hasSignature "tSQW/v3RNPXSGp6fCefGhTlkJbdLjQFLbi9083DuWMRudTh+yq9ppvyCa7O03gt9mvzZsAJ1Cl7m/xcrToA5/Afle20Y33IvGtrxpm5ULH5ajJW7K5mScKjz6iBXCxqqnVGtC6qr/b2vVOO7gl5JElfT9i8/nYm/q28xnKC3oZE=";
        npx:hasSignatureTarget this:;
        npx:signedBy orcid:0000-0002-1267-0234 .
    
    this: dct:created "2024-06-04T07:59:44.344Z"^^xsd:dateTime;
        dct:creator orcid:0000-0002-1267-0234;
        dct:license <https://creativecommons.org/licenses/by/4.0/>;
        npx:introduces sub:setting;
        npx:wasCreatedAt <https://nanodash.knowledgepixels.com/>;
        rdfs:label "Nanopublication setting: first nanopublication setting";
        prov:wasDerivedFrom <https://w3id.org/np/RApvJxJO7tJFbhu0sqfO09XVOxxH9_-IO5EzztJqHMitk>;
        nt:wasCreatedFromProvenanceTemplate <http://purl.org/np/RANwQa4ICWS5SOjw7gp99nBpXBasapwtZF1fIM3H2gYTM>;
        nt:wasCreatedFromPubinfoTemplate <http://purl.org/np/RAA2MfqdBCzmz9yVWjKLXNbyfBNcwsMmOqcNUxkk1maIM>,
        <http://purl.org/np/RABngHbKpoJ3U9Nebc8mX_KUdv_vXw28EejqAyQya5zVA>, <http://purl.org/np/RAh1gm83JiG5M6kDxXhaYT1l49nCzyrckMvTzcPn-iv90>;
        nt:wasCreatedFromTemplate <http://purl.org/np/RA-nvwU310EzeV5EGDaTQAAD6pNgxpa9htP-ImbXBrXO4> .
    }