{
 "title": "Nanopub services",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Infrastructure Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU cores used by Query instances",
     "type": "timeseries",
     "description": "The CPU usage is computed for the last 5 minutes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100* sum by (pod) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"default\",\n    pod=~\".*query-application.*\",\n    container!=\"\",\n    image!=\"\"\n  }[5m])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RAM reserved by Query instances",
     "type": "timeseries",
     "description": "The RAM usage is averaged over the last 5 minutes. It is the total, non-reclaimable RAM taken by the container.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  avg_over_time(container_memory_working_set_bytes{\n    namespace=\"default\",\n    pod=~\".*query-application.*\",\n    container!=\"\",\n    image!=\"\"\n  }[5m])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU cores used by RDF4J instances",
     "type": "timeseries",
     "description": "CPU usage averaged over last 5 minutes for clarity",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * sum by (pod) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"default\",\n    pod=~\".*rdf4j.*\",\n    container!=\"\",\n    image!=\"\"\n  }[5m])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RAM reserved by RDF4J instances",
     "type": "timeseries",
     "description": "The RAM usage is averaged over the last 5 minutes. It is the total, non-reclaimable RAM taken by the container.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  avg_over_time(container_memory_working_set_bytes{\n    namespace=\"default\",\n    pod=~\".*query-rdf4j.*\",\n    container!=\"\",\n    image!=\"\"\n  }[5m])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU cores used by Registry instances",
     "type": "timeseries",
     "description": "The CPU usage is computed for the last 5 minutes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*sum by (pod) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"default\",\n    pod=~\".*registry-application.*\",\n    container!=\"\",\n    image!=\"\"\n  }[5m])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RAM reserved by Registry instances",
     "type": "timeseries",
     "description": "The RAM usage is averaged over the last 5 minutes. It is the total, non-reclaimable RAM taken by the container.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  avg_over_time(container_memory_working_set_bytes{\n    namespace=\"default\",\n    pod=~\".*registry-application.*\",\n    container!=\"\",\n    image!=\"\"\n  }[5m])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU cores used by Mongo instances",
     "type": "timeseries",
     "description": "The CPU usage is computed for the last 5 minutes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*sum by (pod) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"default\",\n    pod=~\".*registry-db.*\",\n    container!=\"\",\n    image!=\"\"\n  }[5m])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RAM reserved by Mongo instances",
     "type": "timeseries",
     "description": "The RAM usage is averaged over the last 5 minutes. It is the total, non-reclaimable RAM taken by the container.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  avg_over_time(container_memory_working_set_bytes{\n    namespace=\"default\",\n    pod=~\".*registry-db.*\",\n    container!=\"\",\n    image!=\"\"\n  }[5m])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU load (1min avg) per node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "node_load1 * 100", "legendFormat": "{{node}}" }
     ]
    }
   ]
  },
  {
   "title": "Nanopublication Network Metrics (Query)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Loaded Nanopublications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum by (instance)( registry_load_counter{job=\"query-pods\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Instance Readiness",
   "type": "timeseries",
   "description": "For visualization purposes numbers between 0 and 1 are given to the server statuses of the Query",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum by (instance) (max without (status) (\n  (registry_server_status{status=\"LAUNCHING\"}*0.1) or\n  (registry_server_status{status=\"LOADING_INITIAL\"}*0.3\n) or (\n  registry_server_status{status=\"LOADING_UPDATES\"}*0.8\n) or (\n  registry_server_status{status=\"READY\"}*1\n) ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Type Repositories",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(instance) (registry_type_repositories_counter{job=\"query-pods\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pubkey Repositories",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(instance) (registry_pubkey_repositories_counter{job=\"query-pods\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Full Repositories",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(instance) (registry_full_repositories_counter{job=\"query-pods\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nanopublication Network Metrics (Registry)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Loaded Nanopublications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (instance) (registry_load_counter{job=\"registry-pods\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registry Instance Readiness",
   "type": "timeseries",
   "description": "Based on registry state, assigns a numerical value between 0 and 1 to monitor the process of the application becoming ready",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by (instance) (max without (status) (\n  (registry_server_status{status=\"launching\"}*0.1) or\n  (registry_server_status{status=\"coreLoading\"}*0.3\n) or (\n  registry_server_status{status=\"coreReady\"}*0.6\n) or (\n  registry_server_status{status=\"ready\"}*1\n) or (registry_server_status{status=\"updating\"}*0.8)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registry Agent Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (instance) (registry_agent_count{job=\"registry-pods\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registry Account Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (instance) (registry_account_count{job=\"registry-pods\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trust State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (instance) (registry_trust_state_counter{job=\"registry-pods\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}