apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  {{- if not .Values.application.autoscaling.enabled }}
  replicas: {{ .Values.application.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "application.labels" . | nindent 8 }}
    spec:
      {{- with .Values.application.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.application.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.application.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.application.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.application.podSecurityContext | nindent 8 }}
      containers:
        - name: application
          securityContext:
            {{- toYaml .Values.application.securityContext | nindent 12 }}
          image: "{{ .Values.application.image.repository }}:{{ .Values.application.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.application.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.application.service.containerPort }}
              protocol: {{ .Values.application.service.protocol }}
            - containerPort: {{ .Values.application.metrics.containerPort }}
              protocol: {{ .Values.application.metrics.protocol }}
          resources:
            {{- toYaml .Values.application.resources | nindent 12 }}
          env:
            - name: REGISTRY_DB_HOST
              value: {{ include "db.fullname" . }}
          volumeMounts:
            - name: setting-trig
              mountPath: /data
              readOnly: true
      volumes:
        - name: setting-trig
          configMap:
            name: "setting-{{ include "application.fullname" . }}"